### ISSUE TITLE
ColumnFilter demo error

### ISSUE THREAD

**Issue by AlexandruIstrate** [iceteagroup/wisej-extensions#74] opened 2020-08-22 12:49 UTC
There is a problem with the demo for ```Wisej.Web.Ext.ColumnFilter```. This is the demo referenced in the tutorial [here](https://wisej.com/blog/columnfilter/).
Essentially, what happens is that whenever I click the filter button on the column I get an error message saying that a method cannot be found. This happens for all of the columns.

**Steps to Reproduce**

1. Open the demo at http://demo.wisej.com/ColumnFilter
2. Click any of the filter buttons on the column headers

**Sample Image**
![image](https://user-images.githubusercontent.com/38143225/90956349-6e957900-e48e-11ea-9df4-d3fbada578a6.png)

**Environment**
**OS**: Windows 10 Enterprise Version 2004 (64 Bit)
**Browser**: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

I would really appreciate having this fixed since I want to implement the same behavior in my app and the demo would be very handy for understanding how the control works.

**Comment by lucapivato** [comment] 2020-08-22 14:49
A MethodNotFound exception in .NET means that the compiled assembly is different from the one referenced by the app.

Did you recompile the ColumnFilter extension and sample from the latest sources?

**Comment by AlexandruIstrate** [comment] 2020-08-22 15:54
I didn't compile the sources. The issue is with the demo page that you have on http://demo.wisej.com/ColumnFilter, not with my project. Do the filters work for you there?

**Comment by lucapivato** [comment] 2020-08-22 17:59
I get the same error when trying the demo site. It's caused by an update to the Wisej framework without an update to the test project. If you run the demo project it works:

https://github.com/iceteagroup/wisej-examples

![image](https://user-images.githubusercontent.com/37640802/90962669-b2cd4d00-e47f-11ea-85ec-84affdc8dfd8.png)

**Comment by AlexandruIstrate** [comment] 2020-08-22 18:33
Alright, then. I guess I'll try the test project instead.
Thanks for the help!

**Comment by LRufenacht** [comment] 2020-08-22 18:34
I updated http://demo.wisej.com/ColumnFilter as well so the filtering should be fixed!

Best,
Levie

**Comment by AlexandruIstrate** [comment] 2020-08-22 20:23
That's great! Now it works perfectly.

**Closed as completed** 2020-08-22 20:33 UTC
Labels: question, done
